### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by kassane** [TheAlgorithms/Algorithms-Zig#1]
I plan to gradually add new algorithms as examples.

[The Algorithms](https://github.com/TheAlgorithms) will a reference, which covers several languages and their respective mechanisms.

If there are contributions I will be grateful, because any help would add to all.

**Comment by kassane** [comment]
@Panquesito7 , would it be trivial to join the project later as part of The Algorithms?
Depending on progress, single contribution can be slower and also prone to bugs without fixes.

**Comment by Panquesito7** [comment]
Hey there! This would be very interesting. We can look into adding it to The Algorithms.
Feel free to contact me via Discord and we can discuss it: Panquesito7#3723

CC: @AnupKumarPanwar, @raklaptudirm, @appgurueu.

**Comment by appgurueu** [comment]
I'd be interested in a Zig repo. I'm not really familiar with the language (yet) though.

**Comment by kassane** [comment]
> I'd be interested in a Zig repo. I'm not really familiar with the language (yet) though.

Nice! The most practical thing I can suggest is to use ziglings:
https://github.com/ratfactor/ziglings

**Comment by kassane** [comment]
More algorithms added & CI/CD

Note: this algorithms added on 6a0ff0c802979a1d526a2f4b5c8b5bcac74dda28 are found in [zig - official documentation](https://ziglang.org/documentation).

**Comment by kassane** [comment]
Performed a new update containing a threadpool example (also compatible with zig version 0.10).

I opted for the master version upgrade (yet), with a future release v0.11 in May (along with LLVM16). In which there were some pertinent changes like:

- package management MVP (initial support), style go-like or D (dub.json);
- HTTP and TLS (client) support;
- refactoring for-loop (see my last commit on this project);
- refactoring `build.zig` with modules and package support;

**Comment by AnupKumarPanwar** [comment]
Sure I'll create a repo for Zig in The Algorithms. You can maintain that.

**Comment by Panquesito7** [comment]
Feel free to create a PR to incorporate the changes.
We could also do a transfer, but it could be a bit messy.

You would need to transfer it to Anup, then Anup can transfer it to the organization (if Anup wants).

**Comment by kassane** [comment]
> Sure I'll create a repo for Zig in The Algorithms. You can maintain that.

@AnupKumarPanwar, ~~I can transfer it to you. See request!!~~
I have just seen the invitation and transfer to the organization.

Replace/rename: `https://github.com/TheAlgorithms/Algorithms-Zig` to `https://github.com/TheAlgorithms/Zig`

**Comment by AnupKumarPanwar** [comment]
Thanks @kassane . This is really awesome.
